---
- name: Collect Memory of HDFS servers
  set_fact: indivisual_ram="{{ hostvars[item]['ansible_memtotal_mb'] }}"
  with_items: "{{ groups['hadoop_datanodes'] }}"
  register: ram_result

- name: Make a list of collected memory
  set_fact: memory_list="{{ ram_result.results | map(attribute='ansible_facts.indivisual_ram') | list }}"

- name: Compute total memmory of server
  set_fact: total_ram="{{ memory_list  | map('int') | sum(start=0) }}"

#  - debug: var=total_ram

- name: Collect CPU of HDFS servers
  set_fact: indivisual_cpu_count="{{ hostvars[item]['ansible_processor_vcpus'] }}"
  with_items: "{{ groups['hadoop_datanodes'] }}"
  register: cpu_result

- name: Make a list of collected cpu count
  set_fact: cpu_list="{{ cpu_result.results | map(attribute='ansible_facts.indivisual_cpu_count') | list }}"

- name: Compute total cpu count
  set_fact: total_cpu_count="{{ cpu_list | map('int') | sum(start=0) }}"

#  - debug: var=total_cpu_count

- name: Get the 80% of total ram for Yarn
  shell: "echo $((80*{{ total_ram }}/100))"
  register: ram_60_prc


- include: hadoop.yml
  become: true
  become_user: "{{ hadoop_user }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_clients'] }}"


- include: configureHdfs.yml
  become: true
  become_user: "{{ hadoop_user }}"

- include: configureVars.yml
  delegate_to: "{{ item }}"
  with_items: "{{ groups['hadoop_clients'] }}"

#systemd
- name: Updating system files path for RedHat family 
  set_fact: systemd_services_dir: /usr/lib/systemd/system 
  when: ansible_os_family == 'RedHat'
    
- name: Updating system files path for Debian family
  set_fact: systemd_services_dir: /lib/systemd/system
  when: ansible_os_family == 'Debian'

- name: Updating systemd restart to default 
  set_fact: restart=no
  when: setup_monit

- name: Updating systemd restart to always  
  set_fact: restart=always
  when: not setup_monit

- include: monit.yml
  when: setup_monit

- include: systemdService.yml

- include: setupHdfs.yml
  become: true
  become_user: "{{ hadoop_user }}"


