---

- name: Copy namenode service script
  template:
    src: namenode-service.j2
    dest: "{{ systemd_services_dir }}/namenode.service"
  
- name: Copy datanode service script
  template:
    src: datanode-service.j2
    dest: "{{ systemd_services_dir }}/datanode.service"
  
- name: Copy secondary namenode service script
  template:
    src: secondarynamenode-service.j2
    dest: "{{ systemd_services_dir }}/secondarynamenode.service"
  
- name: Copy node manager service script
  template:
    src: nodemanager-service.j2
    dest: "{{ systemd_services_dir }}/nodemanager.service"
  
- name: Copy resource manager service script
  template:
    src: resourcemanager-service.j2
    dest: "{{ systemd_services_dir }}/resourcemanager.service"
  
- name: Copy job history service script
  template:
    src: jobhistoryserver-service.j2
    dest: "{{ systemd_services_dir }}/jobhistoryserver.service"
 
- name: Start namenode service
  shell: "sudo systemctl start namenode"
  args:
    executable: /bin/bash
 
- name: Start datanode service
  shell: "sudo systemctl start datanode"
  args:
    executable: /bin/bash

- name: Start secondary namenode service
  shell: "sudo systemctl start secondarynamenode"
  args:
    executable: /bin/bash

- name: Start node manager service
  shell: "sudo systemctl start nodemanager"
  args:
    executable: /bin/bash

- name: Start resource manager service
  shell: "sudo systemctl start resourcemanager"
  args:
    executable: /bin/bash

- name: Start job history service
  shell: "sudo systemctl start jobhistoryserver"
  args:
    executable: /bin/bash

- name: Enable namenode service
  shell: "sudo systemctl enable namenode"
  args:
    executable: /bin/bash

- name: Enable datanode service
  shell: "sudo systemctl enable datanode"
  args:
    executable: /bin/bash

- name: Enable secondary namenode service
  shell: "sudo systemctl enable secondarynamenode"
  args:
    executable: /bin/bash

- name: Enable node manager service
  shell: "sudo systemctl enable nodemanager"
  args:
    executable: /bin/bash

- name: Enable resource manager service
  shell: "sudo systemctl enable resourcemanager"
  args:
    executable: /bin/bash

- name: Enable job history service
  shell: "sudo systemctl enable jobhistoryserver"
  args:
    executable: /bin/bash


######################################################################################
