---

- name: Copy Spark Master service script
  template:
    src: spark-master-service.j2
    dest: "{{ spark_services_dir }}/spark-master.service"

- name: Copy Spark History Server service script
  template:
    src: spark-historyserver-service.j2
    dest: "{{ spark_services_dir }}/spark-historyserver.service"

- name: Copy Spark Slave service script
  template:
    src: spark-slaves-service.j2
    dest: "{{ spark_services_dir }}/spark-slaves.service"

- name: Copy Spark Master Monit service
  template:
    src: monit-spark-master.j2
    dest: /etc/monit.d/service-spark-master
  when: setup_monit

- name: Copy Spark History Server Monit service
  template:
    src: monit-spark-history.j2
    dest: /etc/monit.d/service-spark-history
  when: setup_monit

- name: Copy Spark slave Monit service
  template:
    src: monit-spark-slave.j2
    dest: /etc/monit.d/service-spark-slave
  when: setup_monit

- name: Start Spark Master service
  shell: "sudo systemctl start spark-master"
  args:
    executable: /bin/bash

- name: Start Spark History Server service
  shell: "sudo systemctl start spark-historyserver"
  args:
    executable: /bin/bash

- name: Start Spark Slaves service
  shell: "sudo systemctl start spark-slaves"
  args:
    executable: /bin/bash

- name: Enable Spark Master service
  shell: "sudo systemctl enable spark-master"
  args:
    executable: /bin/bash

- name: Enable Spark History Server service
  shell: "sudo systemctl enable spark-historyserver"
  args:
    executable: /bin/bash

- name: Enable Spark Slaves service
  shell: "sudo systemctl enable spark-slaves"
  args:
    executable: /bin/bash
