---
- name: Copy namenode service script
  template:
    src: namenode-service.j2
    dest: "{{ systemd_services_dir }}/namenode.service"
  
- name: Copy datanode service script
  template:
    src: datanode-service.j2
    dest: "{{ systemd_services_dir }}/datanode.service"
- name: Start Metastore service
  shell: "{{ hive_services_dir }}/service-metastore.sh"
  args:
    executable: /bin/bash


- name: Copy Hive Metastore Monit service
  template:
    src: monit-metastore.j2
    dest: /etc/monit.d/service-metastore
  when: setup_monit

- name: Start resource manager service
  shell: "sudo systemctl start resourcemanager"
  args:
    executable: /bin/bash

- name: Start job history service
  shell: "sudo systemctl start jobhistoryserver"
  args:
    executable: /bin/bash

- name: Enable namenode service
  shell: "sudo systemctl enable namenode"
  args:
    executable: /bin/bash

- name: Enable datanode service
  shell: "sudo systemctl enable datanode"
  args:
    executable: /bin/bash
