---

- name: Start namenode service
  shell: "sudo systemctl start namenode"
  args:
    executable: /bin/bash
 
- name: Start datanode service
  shell: "sudo systemctl start datanode"
  args:
    executable: /bin/bash

- name: Start secondary namenode service
  shell: "sudo systemctl start secondarynamenode"
  args:
    executable: /bin/bash

- name: Start node manager service
  shell: "sudo systemctl start nodemanager"
  args:
    executable: /bin/bash

- name: Start resource manager service
  shell: "sudo systemctl start resourcemanager"
  args:
    executable: /bin/bash

- name: Start job history service
  shell: "sudo systemctl start jobhistoryserver"
  args:
    executable: /bin/bash

- name: Start Hive Metastore service
  shell: "sudo systemctl start metastore"
  args:
    executable: /bin/bash

- name: Start Hive Server2 service
  shell: "sudo systemctl start hiveserver2"
  args:
    executable: /bin/bash

- name: Start Spark Master service
  shell: "sudo systemctl start spark-master"
  args:
    executable: /bin/bash

- name: Start Spark History Server service
  shell: "sudo systemctl start spark-historyserver"
  args:
    executable: /bin/bash

- name: Start Spark Slaves service
  shell: "sudo systemctl start spark-slaves"
  args:
    executable: /bin/bash

- name: Start Monit
  service:
    name: monit
    state: started
  when: setup_monit
